name: recipe_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.6.0+5

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  # Base
  nb_utils: ^4.4.11
  intl: ^0.17.0
  html: ^0.15.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  google_fonts: 2.2.0

  # IMAGES
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+6
  photo_view: ^0.13.0

  # TOOLS
  flutter_vector_icons: ^1.0.0

  #Loacl Database
  sqflite: ^2.0.2
  path_provider: ^2.0.8

  # Firebase
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  google_sign_in: ^5.2.3

  the_apple_sign_in: ^1.1.1

  # CONNECTIVITY
  share_plus: ^3.0.4
  url_launcher: ^6.0.18
  package_info_plus: ^1.3.0
  http: ^0.13.4
  share: ^2.0.4
  flutter_tts: ^3.3.3
  auto_size_text: ^3.0.0

  percent_indicator: ^4.0.0
  numberpicker: ^2.1.1
  step_progress_indicator: ^1.0.2
  google_mobile_ads: ^1.0.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  #flutter run -d chrome --web-hostname localhost --web-port 5000

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/flag/


